Import("env")

env.Append(
    CPPPATH=[
        "#/lib/infrared/encoder_decoder",
        "#/lib/infrared/worker",
        "#/lib/infrared/signal",
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
)
