Import("env")

env.Append(
    CPPPATH=[
        "#/lib/mjs",
    ],
)

libenv = env.Clone(FW_LIB_NAME="mjs")
libenv.ApplyLibFlags()

libenv.AppendUnique(
    CCFLAGS=[
        "-Wno-redundant-decls",
        "-Wno-unused-function",
    ],
)

sources = libenv.GlobRecursive("*.c*")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
