Import("env")


env.Append(
    CPPPATH=[
        "#/",
        "#/lib",
        # Ugly hack
        Dir("../assets/compiled"),
        Dir("../../icons"),
        # Headers for libraries moved to fap_private_libs
        "#/lib/subghz",
        "#/lib/nfc",
        "#/lib/ibutton",
        "#/lib/lfrfid",
        "#/lib/one_wire",
        "#/lib/infrared/encoder_decoder",
        "#/lib/infrared/worker",
        "#/lib/infrared/signal",
        "#/lib/mjs",
    ],
)


libs = env.BuildModules(
    [
        "mlib",
        "stm32wb",
        "freertos",
        "print",
        "microtar",
        "mbedtls",
        "toolbox",
        "libusb_stm32",
        "drivers",
        "fatfs",
        "flipper_format",
        "digital_signal",
        "pulse_reader",
        "signal_reader",
        "u8g2",
        "flipper_application",
        "music_worker",
        "uzlib",
        "nanopb",
        "update_util",
        "momentum",
        "heatshrink",
        "ble_profile",
        "bit_lib",
        "datetime",
        "ieee754_parse_wrap",
    ],
)

Return("libs")
