/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "moon_companion.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(moon_companion_v1_MoonRequest, moon_companion_v1_MoonRequest, 2)


PB_BIND(moon_companion_v1_MoonResponse, moon_companion_v1_MoonResponse, 2)


PB_BIND(moon_companion_v1_MoonEvent, moon_companion_v1_MoonEvent, AUTO)


PB_BIND(moon_companion_v1_MoonPhoneMessage, moon_companion_v1_MoonPhoneMessage, 2)


PB_BIND(moon_companion_v1_PairRequest, moon_companion_v1_PairRequest, AUTO)


PB_BIND(moon_companion_v1_PairResponse, moon_companion_v1_PairResponse, AUTO)


PB_BIND(moon_companion_v1_GetPositionRequest, moon_companion_v1_GetPositionRequest, AUTO)


PB_BIND(moon_companion_v1_PositionData, moon_companion_v1_PositionData, AUTO)


PB_BIND(moon_companion_v1_SubscribePositionRequest, moon_companion_v1_SubscribePositionRequest, AUTO)


PB_BIND(moon_companion_v1_UnsubscribePositionRequest, moon_companion_v1_UnsubscribePositionRequest, AUTO)


PB_BIND(moon_companion_v1_GetTimeRequest, moon_companion_v1_GetTimeRequest, AUTO)


PB_BIND(moon_companion_v1_TimeData, moon_companion_v1_TimeData, AUTO)


PB_BIND(moon_companion_v1_SendNotificationRequest, moon_companion_v1_SendNotificationRequest, 2)


PB_BIND(moon_companion_v1_NotificationAck, moon_companion_v1_NotificationAck, AUTO)


PB_BIND(moon_companion_v1_StatusAck, moon_companion_v1_StatusAck, AUTO)


PB_BIND(moon_companion_v1_PhoneStatus, moon_companion_v1_PhoneStatus, AUTO)


PB_BIND(moon_companion_v1_ListAppUpdatesRequest, moon_companion_v1_ListAppUpdatesRequest, 2)


PB_BIND(moon_companion_v1_AppVersion, moon_companion_v1_AppVersion, AUTO)


PB_BIND(moon_companion_v1_UpdateList, moon_companion_v1_UpdateList, 2)


PB_BIND(moon_companion_v1_AvailableUpdate, moon_companion_v1_AvailableUpdate, AUTO)


PB_BIND(moon_companion_v1_DownloadAppRequest, moon_companion_v1_DownloadAppRequest, AUTO)


PB_BIND(moon_companion_v1_CheckFirmwareUpdateRequest, moon_companion_v1_CheckFirmwareUpdateRequest, AUTO)


PB_BIND(moon_companion_v1_HttpGetRequest, moon_companion_v1_HttpGetRequest, 2)


PB_BIND(moon_companion_v1_HttpPostRequest, moon_companion_v1_HttpPostRequest, 2)


PB_BIND(moon_companion_v1_HttpHeader, moon_companion_v1_HttpHeader, AUTO)


PB_BIND(moon_companion_v1_HttpResponse, moon_companion_v1_HttpResponse, 2)






