/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_MOON_COMPANION_V1_MOON_COMPANION_PB_H_INCLUDED
#define PB_MOON_COMPANION_V1_MOON_COMPANION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _moon_companion_v1_MoonStatus {
    moon_companion_v1_MoonStatus_MOON_OK = 0,
    moon_companion_v1_MoonStatus_MOON_UNAUTHORIZED = 1, /* auth_token missing or wrong */
    moon_companion_v1_MoonStatus_MOON_UNSUPPORTED_VERSION = 2,
    moon_companion_v1_MoonStatus_MOON_UNSUPPORTED_REQUEST = 3, /* phone doesn't implement this yet */
    moon_companion_v1_MoonStatus_MOON_INTERNAL_ERROR = 4,
    moon_companion_v1_MoonStatus_MOON_NOT_AVAILABLE = 5, /* e.g., GPS not fixed, no network */
    moon_companion_v1_MoonStatus_MOON_RATE_LIMITED = 6
} moon_companion_v1_MoonStatus;

typedef enum _moon_companion_v1_FixQuality {
    moon_companion_v1_FixQuality_FIX_NONE = 0,
    moon_companion_v1_FixQuality_FIX_2D = 1,
    moon_companion_v1_FixQuality_FIX_3D = 2
} moon_companion_v1_FixQuality;

typedef enum _moon_companion_v1_SendNotificationRequest_Priority {
    moon_companion_v1_SendNotificationRequest_Priority_NORMAL = 0,
    moon_companion_v1_SendNotificationRequest_Priority_HIGH = 1,
    moon_companion_v1_SendNotificationRequest_Priority_URGENT = 2
} moon_companion_v1_SendNotificationRequest_Priority;

/* Struct definitions */
typedef struct _moon_companion_v1_PairRequest {
    char flipper_name[32]; /* purely for the phone's UI */
} moon_companion_v1_PairRequest;

typedef PB_BYTES_ARRAY_T(16) moon_companion_v1_PairResponse_auth_token_t;
typedef struct _moon_companion_v1_PairResponse {
    moon_companion_v1_PairResponse_auth_token_t auth_token; /* 16 bytes; caller persists and sends in every MoonRequest */
    char phone_name[32]; /* purely for the Flipper's UI */
} moon_companion_v1_PairResponse;

typedef struct _moon_companion_v1_GetPositionRequest {
    uint32_t max_age_ms; /* return cached fix if younger than this; 0 = any age */
} moon_companion_v1_GetPositionRequest;

typedef PB_BYTES_ARRAY_T(8) moon_companion_v1_PositionData_source_id_t;
typedef struct _moon_companion_v1_PositionData {
    int32_t lat_e7; /* latitude  × 1e7 */
    int32_t lon_e7; /* longitude × 1e7 */
    int32_t alt_mm; /* altitude above WGS-84 ellipsoid, mm */
    uint32_t accuracy_mm; /* 68 %-CEP horizontal accuracy */
    uint32_t speed_mmps; /* speed over ground, mm/s */
    uint32_t heading_cdeg; /* 0 – 35999 (0.01 degree) */
    uint64_t timestamp_ms; /* Unix epoch ms when the fix was taken */
    moon_companion_v1_FixQuality fix_quality;
    uint32_t satellites;
    /* Identifier of the upstream source that produced this fix. The paired
 phone fills this with the first 8 bytes of its stable device ID so
 the Flipper service can distinguish multiple sources (phone vs. a
 future Meshtastic bridge vs. a dedicated GPS module) if we ever
 plumb more than one. Zero-filled when the source doesn't have a
 stable identity or doesn't care. */
    moon_companion_v1_PositionData_source_id_t source_id; /* 8 bytes, max */
} moon_companion_v1_PositionData;

typedef struct _moon_companion_v1_SubscribePositionRequest {
    uint32_t interval_ms; /* push interval; phone may clamp to min 500 ms */
} moon_companion_v1_SubscribePositionRequest;

typedef struct _moon_companion_v1_UnsubscribePositionRequest {
    char dummy_field;
} moon_companion_v1_UnsubscribePositionRequest;

typedef struct _moon_companion_v1_GetTimeRequest {
    char dummy_field;
} moon_companion_v1_GetTimeRequest;

typedef struct _moon_companion_v1_TimeData {
    uint64_t unix_ms;
    int32_t tz_offset_seconds; /* e.g., -14400 for EDT */
    char tz_name[48]; /* IANA name, e.g. "America/New_York" */
} moon_companion_v1_TimeData;

typedef struct _moon_companion_v1_SendNotificationRequest {
    char title[64];
    char body[160];
    moon_companion_v1_SendNotificationRequest_Priority priority;
    char tag[32]; /* optional: phone dedupes by tag, replaces prior with same tag */
} moon_companion_v1_SendNotificationRequest;

typedef struct _moon_companion_v1_NotificationAck {
    bool delivered;
} moon_companion_v1_NotificationAck;

typedef struct _moon_companion_v1_StatusAck {
    char dummy_field;
} moon_companion_v1_StatusAck;

typedef struct _moon_companion_v1_PhoneStatus {
    uint32_t battery_pct;
    bool charging;
    bool has_network;
} moon_companion_v1_PhoneStatus;

/* Phone-initiated push. No request_id; phone emits these on its own
 schedule (e.g. once per second for a position subscription). */
typedef struct _moon_companion_v1_MoonEvent {
    pb_size_t which_event;
    union {
        moon_companion_v1_PositionData position_update;
        moon_companion_v1_PhoneStatus phone_status;
    } event;
} moon_companion_v1_MoonEvent;

typedef struct _moon_companion_v1_AppVersion {
    char appid[32];
    char version[16];
} moon_companion_v1_AppVersion;

typedef struct _moon_companion_v1_ListAppUpdatesRequest {
    pb_size_t installed_count;
    moon_companion_v1_AppVersion installed[8];
} moon_companion_v1_ListAppUpdatesRequest;

typedef struct _moon_companion_v1_AvailableUpdate {
    char appid[32];
    char new_version[16];
    char source_url[128]; /* phone uses this to fetch via HTTP, then streams over CoC */
    uint32_t size_bytes;
} moon_companion_v1_AvailableUpdate;

typedef struct _moon_companion_v1_UpdateList {
    pb_size_t updates_count;
    moon_companion_v1_AvailableUpdate updates[8];
} moon_companion_v1_UpdateList;

typedef struct _moon_companion_v1_DownloadAppRequest {
    char appid[32];
    char source_url[128]; /* from AvailableUpdate.source_url */
} moon_companion_v1_DownloadAppRequest;

typedef struct _moon_companion_v1_CheckFirmwareUpdateRequest {
    char current_version[16];
} moon_companion_v1_CheckFirmwareUpdateRequest;

typedef struct _moon_companion_v1_HttpHeader {
    char key[32];
    char value[128];
} moon_companion_v1_HttpHeader;

typedef struct _moon_companion_v1_HttpGetRequest {
    char url[128];
    pb_size_t headers_count;
    moon_companion_v1_HttpHeader headers[4];
} moon_companion_v1_HttpGetRequest;

typedef PB_BYTES_ARRAY_T(128) moon_companion_v1_HttpPostRequest_body_t;
typedef struct _moon_companion_v1_HttpPostRequest {
    char url[128];
    pb_size_t headers_count;
    moon_companion_v1_HttpHeader headers[4];
    moon_companion_v1_HttpPostRequest_body_t body;
} moon_companion_v1_HttpPostRequest;

typedef PB_BYTES_ARRAY_T(16) moon_companion_v1_MoonRequest_auth_token_t;
typedef struct _moon_companion_v1_MoonRequest {
    uint32_t request_id; /* echoed in MoonResponse.request_id */
    moon_companion_v1_MoonRequest_auth_token_t auth_token; /* 16 bytes from pairing (MoonPair) */
    pb_size_t which_payload;
    union {
        /* Pairing (Phase 1) */
        moon_companion_v1_PairRequest pair;
        /* Tier 1 — MVP */
        moon_companion_v1_GetPositionRequest get_position;
        moon_companion_v1_SubscribePositionRequest subscribe_position;
        moon_companion_v1_UnsubscribePositionRequest unsubscribe_position;
        moon_companion_v1_GetTimeRequest get_time;
        moon_companion_v1_SendNotificationRequest send_notification;
        /* Tier 2 — stubs for now, filled in later */
        moon_companion_v1_ListAppUpdatesRequest list_app_updates;
        moon_companion_v1_DownloadAppRequest download_app;
        moon_companion_v1_CheckFirmwareUpdateRequest check_firmware;
        moon_companion_v1_HttpGetRequest http_get;
        moon_companion_v1_HttpPostRequest http_post;
    } payload;
} moon_companion_v1_MoonRequest;

typedef PB_BYTES_ARRAY_T(128) moon_companion_v1_HttpResponse_body_t;
typedef struct _moon_companion_v1_HttpResponse {
    uint32_t status_code;
    pb_size_t headers_count;
    moon_companion_v1_HttpHeader headers[4];
    moon_companion_v1_HttpResponse_body_t body;
} moon_companion_v1_HttpResponse;

typedef struct _moon_companion_v1_MoonResponse {
    uint32_t request_id;
    moon_companion_v1_MoonStatus status;
    pb_size_t which_payload;
    union {
        moon_companion_v1_PairResponse pair;
        moon_companion_v1_PositionData position;
        moon_companion_v1_TimeData time;
        moon_companion_v1_NotificationAck notification;
        moon_companion_v1_UpdateList updates;
        moon_companion_v1_HttpResponse http;
        moon_companion_v1_StatusAck ack;
    } payload;
} moon_companion_v1_MoonResponse;

/* Top-level message carried over the RPC_RX characteristic. Every
 phone→Flipper notification is a MoonPhoneMessage so the Flipper-side
 decoder only needs one entry point. */
typedef struct _moon_companion_v1_MoonPhoneMessage {
    pb_size_t which_kind;
    union {
        moon_companion_v1_MoonResponse response;
        moon_companion_v1_MoonEvent event;
    } kind;
} moon_companion_v1_MoonPhoneMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _moon_companion_v1_MoonStatus_MIN moon_companion_v1_MoonStatus_MOON_OK
#define _moon_companion_v1_MoonStatus_MAX moon_companion_v1_MoonStatus_MOON_RATE_LIMITED
#define _moon_companion_v1_MoonStatus_ARRAYSIZE ((moon_companion_v1_MoonStatus)(moon_companion_v1_MoonStatus_MOON_RATE_LIMITED+1))

#define _moon_companion_v1_FixQuality_MIN moon_companion_v1_FixQuality_FIX_NONE
#define _moon_companion_v1_FixQuality_MAX moon_companion_v1_FixQuality_FIX_3D
#define _moon_companion_v1_FixQuality_ARRAYSIZE ((moon_companion_v1_FixQuality)(moon_companion_v1_FixQuality_FIX_3D+1))

#define _moon_companion_v1_SendNotificationRequest_Priority_MIN moon_companion_v1_SendNotificationRequest_Priority_NORMAL
#define _moon_companion_v1_SendNotificationRequest_Priority_MAX moon_companion_v1_SendNotificationRequest_Priority_URGENT
#define _moon_companion_v1_SendNotificationRequest_Priority_ARRAYSIZE ((moon_companion_v1_SendNotificationRequest_Priority)(moon_companion_v1_SendNotificationRequest_Priority_URGENT+1))


#define moon_companion_v1_MoonResponse_status_ENUMTYPE moon_companion_v1_MoonStatus






#define moon_companion_v1_PositionData_fix_quality_ENUMTYPE moon_companion_v1_FixQuality





#define moon_companion_v1_SendNotificationRequest_priority_ENUMTYPE moon_companion_v1_SendNotificationRequest_Priority















/* Initializer values for message structs */
#define moon_companion_v1_MoonRequest_init_default {0, {0, {0}}, 0, {moon_companion_v1_PairRequest_init_default}}
#define moon_companion_v1_MoonResponse_init_default {0, _moon_companion_v1_MoonStatus_MIN, 0, {moon_companion_v1_PairResponse_init_default}}
#define moon_companion_v1_MoonEvent_init_default {0, {moon_companion_v1_PositionData_init_default}}
#define moon_companion_v1_MoonPhoneMessage_init_default {0, {moon_companion_v1_MoonResponse_init_default}}
#define moon_companion_v1_PairRequest_init_default {""}
#define moon_companion_v1_PairResponse_init_default {{0, {0}}, ""}
#define moon_companion_v1_GetPositionRequest_init_default {0}
#define moon_companion_v1_PositionData_init_default {0, 0, 0, 0, 0, 0, 0, _moon_companion_v1_FixQuality_MIN, 0, {0, {0}}}
#define moon_companion_v1_SubscribePositionRequest_init_default {0}
#define moon_companion_v1_UnsubscribePositionRequest_init_default {0}
#define moon_companion_v1_GetTimeRequest_init_default {0}
#define moon_companion_v1_TimeData_init_default  {0, 0, ""}
#define moon_companion_v1_SendNotificationRequest_init_default {"", "", _moon_companion_v1_SendNotificationRequest_Priority_MIN, ""}
#define moon_companion_v1_NotificationAck_init_default {0}
#define moon_companion_v1_StatusAck_init_default {0}
#define moon_companion_v1_PhoneStatus_init_default {0, 0, 0}
#define moon_companion_v1_ListAppUpdatesRequest_init_default {0, {moon_companion_v1_AppVersion_init_default, moon_companion_v1_AppVersion_init_default, moon_companion_v1_AppVersion_init_default, moon_companion_v1_AppVersion_init_default, moon_companion_v1_AppVersion_init_default, moon_companion_v1_AppVersion_init_default, moon_companion_v1_AppVersion_init_default, moon_companion_v1_AppVersion_init_default}}
#define moon_companion_v1_AppVersion_init_default {"", ""}
#define moon_companion_v1_UpdateList_init_default {0, {moon_companion_v1_AvailableUpdate_init_default, moon_companion_v1_AvailableUpdate_init_default, moon_companion_v1_AvailableUpdate_init_default, moon_companion_v1_AvailableUpdate_init_default, moon_companion_v1_AvailableUpdate_init_default, moon_companion_v1_AvailableUpdate_init_default, moon_companion_v1_AvailableUpdate_init_default, moon_companion_v1_AvailableUpdate_init_default}}
#define moon_companion_v1_AvailableUpdate_init_default {"", "", "", 0}
#define moon_companion_v1_DownloadAppRequest_init_default {"", ""}
#define moon_companion_v1_CheckFirmwareUpdateRequest_init_default {""}
#define moon_companion_v1_HttpGetRequest_init_default {"", 0, {moon_companion_v1_HttpHeader_init_default, moon_companion_v1_HttpHeader_init_default, moon_companion_v1_HttpHeader_init_default, moon_companion_v1_HttpHeader_init_default}}
#define moon_companion_v1_HttpPostRequest_init_default {"", 0, {moon_companion_v1_HttpHeader_init_default, moon_companion_v1_HttpHeader_init_default, moon_companion_v1_HttpHeader_init_default, moon_companion_v1_HttpHeader_init_default}, {0, {0}}}
#define moon_companion_v1_HttpHeader_init_default {"", ""}
#define moon_companion_v1_HttpResponse_init_default {0, 0, {moon_companion_v1_HttpHeader_init_default, moon_companion_v1_HttpHeader_init_default, moon_companion_v1_HttpHeader_init_default, moon_companion_v1_HttpHeader_init_default}, {0, {0}}}
#define moon_companion_v1_MoonRequest_init_zero  {0, {0, {0}}, 0, {moon_companion_v1_PairRequest_init_zero}}
#define moon_companion_v1_MoonResponse_init_zero {0, _moon_companion_v1_MoonStatus_MIN, 0, {moon_companion_v1_PairResponse_init_zero}}
#define moon_companion_v1_MoonEvent_init_zero    {0, {moon_companion_v1_PositionData_init_zero}}
#define moon_companion_v1_MoonPhoneMessage_init_zero {0, {moon_companion_v1_MoonResponse_init_zero}}
#define moon_companion_v1_PairRequest_init_zero  {""}
#define moon_companion_v1_PairResponse_init_zero {{0, {0}}, ""}
#define moon_companion_v1_GetPositionRequest_init_zero {0}
#define moon_companion_v1_PositionData_init_zero {0, 0, 0, 0, 0, 0, 0, _moon_companion_v1_FixQuality_MIN, 0, {0, {0}}}
#define moon_companion_v1_SubscribePositionRequest_init_zero {0}
#define moon_companion_v1_UnsubscribePositionRequest_init_zero {0}
#define moon_companion_v1_GetTimeRequest_init_zero {0}
#define moon_companion_v1_TimeData_init_zero     {0, 0, ""}
#define moon_companion_v1_SendNotificationRequest_init_zero {"", "", _moon_companion_v1_SendNotificationRequest_Priority_MIN, ""}
#define moon_companion_v1_NotificationAck_init_zero {0}
#define moon_companion_v1_StatusAck_init_zero    {0}
#define moon_companion_v1_PhoneStatus_init_zero  {0, 0, 0}
#define moon_companion_v1_ListAppUpdatesRequest_init_zero {0, {moon_companion_v1_AppVersion_init_zero, moon_companion_v1_AppVersion_init_zero, moon_companion_v1_AppVersion_init_zero, moon_companion_v1_AppVersion_init_zero, moon_companion_v1_AppVersion_init_zero, moon_companion_v1_AppVersion_init_zero, moon_companion_v1_AppVersion_init_zero, moon_companion_v1_AppVersion_init_zero}}
#define moon_companion_v1_AppVersion_init_zero   {"", ""}
#define moon_companion_v1_UpdateList_init_zero   {0, {moon_companion_v1_AvailableUpdate_init_zero, moon_companion_v1_AvailableUpdate_init_zero, moon_companion_v1_AvailableUpdate_init_zero, moon_companion_v1_AvailableUpdate_init_zero, moon_companion_v1_AvailableUpdate_init_zero, moon_companion_v1_AvailableUpdate_init_zero, moon_companion_v1_AvailableUpdate_init_zero, moon_companion_v1_AvailableUpdate_init_zero}}
#define moon_companion_v1_AvailableUpdate_init_zero {"", "", "", 0}
#define moon_companion_v1_DownloadAppRequest_init_zero {"", ""}
#define moon_companion_v1_CheckFirmwareUpdateRequest_init_zero {""}
#define moon_companion_v1_HttpGetRequest_init_zero {"", 0, {moon_companion_v1_HttpHeader_init_zero, moon_companion_v1_HttpHeader_init_zero, moon_companion_v1_HttpHeader_init_zero, moon_companion_v1_HttpHeader_init_zero}}
#define moon_companion_v1_HttpPostRequest_init_zero {"", 0, {moon_companion_v1_HttpHeader_init_zero, moon_companion_v1_HttpHeader_init_zero, moon_companion_v1_HttpHeader_init_zero, moon_companion_v1_HttpHeader_init_zero}, {0, {0}}}
#define moon_companion_v1_HttpHeader_init_zero   {"", ""}
#define moon_companion_v1_HttpResponse_init_zero {0, 0, {moon_companion_v1_HttpHeader_init_zero, moon_companion_v1_HttpHeader_init_zero, moon_companion_v1_HttpHeader_init_zero, moon_companion_v1_HttpHeader_init_zero}, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define moon_companion_v1_PairRequest_flipper_name_tag 1
#define moon_companion_v1_PairResponse_auth_token_tag 1
#define moon_companion_v1_PairResponse_phone_name_tag 2
#define moon_companion_v1_GetPositionRequest_max_age_ms_tag 1
#define moon_companion_v1_PositionData_lat_e7_tag 1
#define moon_companion_v1_PositionData_lon_e7_tag 2
#define moon_companion_v1_PositionData_alt_mm_tag 3
#define moon_companion_v1_PositionData_accuracy_mm_tag 4
#define moon_companion_v1_PositionData_speed_mmps_tag 5
#define moon_companion_v1_PositionData_heading_cdeg_tag 6
#define moon_companion_v1_PositionData_timestamp_ms_tag 7
#define moon_companion_v1_PositionData_fix_quality_tag 8
#define moon_companion_v1_PositionData_satellites_tag 9
#define moon_companion_v1_PositionData_source_id_tag 10
#define moon_companion_v1_SubscribePositionRequest_interval_ms_tag 1
#define moon_companion_v1_TimeData_unix_ms_tag   1
#define moon_companion_v1_TimeData_tz_offset_seconds_tag 2
#define moon_companion_v1_TimeData_tz_name_tag   3
#define moon_companion_v1_SendNotificationRequest_title_tag 1
#define moon_companion_v1_SendNotificationRequest_body_tag 2
#define moon_companion_v1_SendNotificationRequest_priority_tag 3
#define moon_companion_v1_SendNotificationRequest_tag_tag 4
#define moon_companion_v1_NotificationAck_delivered_tag 1
#define moon_companion_v1_PhoneStatus_battery_pct_tag 1
#define moon_companion_v1_PhoneStatus_charging_tag 2
#define moon_companion_v1_PhoneStatus_has_network_tag 3
#define moon_companion_v1_MoonEvent_position_update_tag 1
#define moon_companion_v1_MoonEvent_phone_status_tag 2
#define moon_companion_v1_AppVersion_appid_tag   1
#define moon_companion_v1_AppVersion_version_tag 2
#define moon_companion_v1_ListAppUpdatesRequest_installed_tag 1
#define moon_companion_v1_AvailableUpdate_appid_tag 1
#define moon_companion_v1_AvailableUpdate_new_version_tag 2
#define moon_companion_v1_AvailableUpdate_source_url_tag 3
#define moon_companion_v1_AvailableUpdate_size_bytes_tag 4
#define moon_companion_v1_UpdateList_updates_tag 1
#define moon_companion_v1_DownloadAppRequest_appid_tag 1
#define moon_companion_v1_DownloadAppRequest_source_url_tag 2
#define moon_companion_v1_CheckFirmwareUpdateRequest_current_version_tag 1
#define moon_companion_v1_HttpHeader_key_tag     1
#define moon_companion_v1_HttpHeader_value_tag   2
#define moon_companion_v1_HttpGetRequest_url_tag 1
#define moon_companion_v1_HttpGetRequest_headers_tag 2
#define moon_companion_v1_HttpPostRequest_url_tag 1
#define moon_companion_v1_HttpPostRequest_headers_tag 2
#define moon_companion_v1_HttpPostRequest_body_tag 3
#define moon_companion_v1_MoonRequest_request_id_tag 1
#define moon_companion_v1_MoonRequest_auth_token_tag 2
#define moon_companion_v1_MoonRequest_pair_tag   3
#define moon_companion_v1_MoonRequest_get_position_tag 10
#define moon_companion_v1_MoonRequest_subscribe_position_tag 11
#define moon_companion_v1_MoonRequest_unsubscribe_position_tag 12
#define moon_companion_v1_MoonRequest_get_time_tag 20
#define moon_companion_v1_MoonRequest_send_notification_tag 30
#define moon_companion_v1_MoonRequest_list_app_updates_tag 100
#define moon_companion_v1_MoonRequest_download_app_tag 101
#define moon_companion_v1_MoonRequest_check_firmware_tag 110
#define moon_companion_v1_MoonRequest_http_get_tag 200
#define moon_companion_v1_MoonRequest_http_post_tag 201
#define moon_companion_v1_HttpResponse_status_code_tag 1
#define moon_companion_v1_HttpResponse_headers_tag 2
#define moon_companion_v1_HttpResponse_body_tag  3
#define moon_companion_v1_MoonResponse_request_id_tag 1
#define moon_companion_v1_MoonResponse_status_tag 2
#define moon_companion_v1_MoonResponse_pair_tag  3
#define moon_companion_v1_MoonResponse_position_tag 10
#define moon_companion_v1_MoonResponse_time_tag  20
#define moon_companion_v1_MoonResponse_notification_tag 30
#define moon_companion_v1_MoonResponse_updates_tag 100
#define moon_companion_v1_MoonResponse_http_tag  200
#define moon_companion_v1_MoonResponse_ack_tag   255
#define moon_companion_v1_MoonPhoneMessage_response_tag 1
#define moon_companion_v1_MoonPhoneMessage_event_tag 2

/* Struct field encoding specification for nanopb */
#define moon_companion_v1_MoonRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   SINGULAR, BYTES,    auth_token,        2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pair,payload.pair),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_position,payload.get_position),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,subscribe_position,payload.subscribe_position),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,unsubscribe_position,payload.unsubscribe_position),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_time,payload.get_time),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,send_notification,payload.send_notification),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,list_app_updates,payload.list_app_updates), 100) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,download_app,payload.download_app), 101) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,check_firmware,payload.check_firmware), 110) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,http_get,payload.http_get), 200) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,http_post,payload.http_post), 201)
#define moon_companion_v1_MoonRequest_CALLBACK NULL
#define moon_companion_v1_MoonRequest_DEFAULT NULL
#define moon_companion_v1_MoonRequest_payload_pair_MSGTYPE moon_companion_v1_PairRequest
#define moon_companion_v1_MoonRequest_payload_get_position_MSGTYPE moon_companion_v1_GetPositionRequest
#define moon_companion_v1_MoonRequest_payload_subscribe_position_MSGTYPE moon_companion_v1_SubscribePositionRequest
#define moon_companion_v1_MoonRequest_payload_unsubscribe_position_MSGTYPE moon_companion_v1_UnsubscribePositionRequest
#define moon_companion_v1_MoonRequest_payload_get_time_MSGTYPE moon_companion_v1_GetTimeRequest
#define moon_companion_v1_MoonRequest_payload_send_notification_MSGTYPE moon_companion_v1_SendNotificationRequest
#define moon_companion_v1_MoonRequest_payload_list_app_updates_MSGTYPE moon_companion_v1_ListAppUpdatesRequest
#define moon_companion_v1_MoonRequest_payload_download_app_MSGTYPE moon_companion_v1_DownloadAppRequest
#define moon_companion_v1_MoonRequest_payload_check_firmware_MSGTYPE moon_companion_v1_CheckFirmwareUpdateRequest
#define moon_companion_v1_MoonRequest_payload_http_get_MSGTYPE moon_companion_v1_HttpGetRequest
#define moon_companion_v1_MoonRequest_payload_http_post_MSGTYPE moon_companion_v1_HttpPostRequest

#define moon_companion_v1_MoonResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pair,payload.pair),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,position,payload.position),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,time,payload.time),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,notification,payload.notification),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,updates,payload.updates), 100) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,http,payload.http), 200) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack), 255)
#define moon_companion_v1_MoonResponse_CALLBACK NULL
#define moon_companion_v1_MoonResponse_DEFAULT NULL
#define moon_companion_v1_MoonResponse_payload_pair_MSGTYPE moon_companion_v1_PairResponse
#define moon_companion_v1_MoonResponse_payload_position_MSGTYPE moon_companion_v1_PositionData
#define moon_companion_v1_MoonResponse_payload_time_MSGTYPE moon_companion_v1_TimeData
#define moon_companion_v1_MoonResponse_payload_notification_MSGTYPE moon_companion_v1_NotificationAck
#define moon_companion_v1_MoonResponse_payload_updates_MSGTYPE moon_companion_v1_UpdateList
#define moon_companion_v1_MoonResponse_payload_http_MSGTYPE moon_companion_v1_HttpResponse
#define moon_companion_v1_MoonResponse_payload_ack_MSGTYPE moon_companion_v1_StatusAck

#define moon_companion_v1_MoonEvent_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,position_update,event.position_update),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,phone_status,event.phone_status),   2)
#define moon_companion_v1_MoonEvent_CALLBACK NULL
#define moon_companion_v1_MoonEvent_DEFAULT NULL
#define moon_companion_v1_MoonEvent_event_position_update_MSGTYPE moon_companion_v1_PositionData
#define moon_companion_v1_MoonEvent_event_phone_status_MSGTYPE moon_companion_v1_PhoneStatus

#define moon_companion_v1_MoonPhoneMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,response,kind.response),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,event,kind.event),   2)
#define moon_companion_v1_MoonPhoneMessage_CALLBACK NULL
#define moon_companion_v1_MoonPhoneMessage_DEFAULT NULL
#define moon_companion_v1_MoonPhoneMessage_kind_response_MSGTYPE moon_companion_v1_MoonResponse
#define moon_companion_v1_MoonPhoneMessage_kind_event_MSGTYPE moon_companion_v1_MoonEvent

#define moon_companion_v1_PairRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   flipper_name,      1)
#define moon_companion_v1_PairRequest_CALLBACK NULL
#define moon_companion_v1_PairRequest_DEFAULT NULL

#define moon_companion_v1_PairResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    auth_token,        1) \
X(a, STATIC,   SINGULAR, STRING,   phone_name,        2)
#define moon_companion_v1_PairResponse_CALLBACK NULL
#define moon_companion_v1_PairResponse_DEFAULT NULL

#define moon_companion_v1_GetPositionRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   max_age_ms,        1)
#define moon_companion_v1_GetPositionRequest_CALLBACK NULL
#define moon_companion_v1_GetPositionRequest_DEFAULT NULL

#define moon_companion_v1_PositionData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SFIXED32, lat_e7,            1) \
X(a, STATIC,   SINGULAR, SFIXED32, lon_e7,            2) \
X(a, STATIC,   SINGULAR, SINT32,   alt_mm,            3) \
X(a, STATIC,   SINGULAR, UINT32,   accuracy_mm,       4) \
X(a, STATIC,   SINGULAR, UINT32,   speed_mmps,        5) \
X(a, STATIC,   SINGULAR, UINT32,   heading_cdeg,      6) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_ms,      7) \
X(a, STATIC,   SINGULAR, UENUM,    fix_quality,       8) \
X(a, STATIC,   SINGULAR, UINT32,   satellites,        9) \
X(a, STATIC,   SINGULAR, BYTES,    source_id,        10)
#define moon_companion_v1_PositionData_CALLBACK NULL
#define moon_companion_v1_PositionData_DEFAULT NULL

#define moon_companion_v1_SubscribePositionRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   interval_ms,       1)
#define moon_companion_v1_SubscribePositionRequest_CALLBACK NULL
#define moon_companion_v1_SubscribePositionRequest_DEFAULT NULL

#define moon_companion_v1_UnsubscribePositionRequest_FIELDLIST(X, a) \

#define moon_companion_v1_UnsubscribePositionRequest_CALLBACK NULL
#define moon_companion_v1_UnsubscribePositionRequest_DEFAULT NULL

#define moon_companion_v1_GetTimeRequest_FIELDLIST(X, a) \

#define moon_companion_v1_GetTimeRequest_CALLBACK NULL
#define moon_companion_v1_GetTimeRequest_DEFAULT NULL

#define moon_companion_v1_TimeData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   unix_ms,           1) \
X(a, STATIC,   SINGULAR, SINT32,   tz_offset_seconds,   2) \
X(a, STATIC,   SINGULAR, STRING,   tz_name,           3)
#define moon_companion_v1_TimeData_CALLBACK NULL
#define moon_companion_v1_TimeData_DEFAULT NULL

#define moon_companion_v1_SendNotificationRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   title,             1) \
X(a, STATIC,   SINGULAR, STRING,   body,              2) \
X(a, STATIC,   SINGULAR, UENUM,    priority,          3) \
X(a, STATIC,   SINGULAR, STRING,   tag,               4)
#define moon_companion_v1_SendNotificationRequest_CALLBACK NULL
#define moon_companion_v1_SendNotificationRequest_DEFAULT NULL

#define moon_companion_v1_NotificationAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     delivered,         1)
#define moon_companion_v1_NotificationAck_CALLBACK NULL
#define moon_companion_v1_NotificationAck_DEFAULT NULL

#define moon_companion_v1_StatusAck_FIELDLIST(X, a) \

#define moon_companion_v1_StatusAck_CALLBACK NULL
#define moon_companion_v1_StatusAck_DEFAULT NULL

#define moon_companion_v1_PhoneStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   battery_pct,       1) \
X(a, STATIC,   SINGULAR, BOOL,     charging,          2) \
X(a, STATIC,   SINGULAR, BOOL,     has_network,       3)
#define moon_companion_v1_PhoneStatus_CALLBACK NULL
#define moon_companion_v1_PhoneStatus_DEFAULT NULL

#define moon_companion_v1_ListAppUpdatesRequest_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  installed,         1)
#define moon_companion_v1_ListAppUpdatesRequest_CALLBACK NULL
#define moon_companion_v1_ListAppUpdatesRequest_DEFAULT NULL
#define moon_companion_v1_ListAppUpdatesRequest_installed_MSGTYPE moon_companion_v1_AppVersion

#define moon_companion_v1_AppVersion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   appid,             1) \
X(a, STATIC,   SINGULAR, STRING,   version,           2)
#define moon_companion_v1_AppVersion_CALLBACK NULL
#define moon_companion_v1_AppVersion_DEFAULT NULL

#define moon_companion_v1_UpdateList_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  updates,           1)
#define moon_companion_v1_UpdateList_CALLBACK NULL
#define moon_companion_v1_UpdateList_DEFAULT NULL
#define moon_companion_v1_UpdateList_updates_MSGTYPE moon_companion_v1_AvailableUpdate

#define moon_companion_v1_AvailableUpdate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   appid,             1) \
X(a, STATIC,   SINGULAR, STRING,   new_version,       2) \
X(a, STATIC,   SINGULAR, STRING,   source_url,        3) \
X(a, STATIC,   SINGULAR, UINT32,   size_bytes,        4)
#define moon_companion_v1_AvailableUpdate_CALLBACK NULL
#define moon_companion_v1_AvailableUpdate_DEFAULT NULL

#define moon_companion_v1_DownloadAppRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   appid,             1) \
X(a, STATIC,   SINGULAR, STRING,   source_url,        2)
#define moon_companion_v1_DownloadAppRequest_CALLBACK NULL
#define moon_companion_v1_DownloadAppRequest_DEFAULT NULL

#define moon_companion_v1_CheckFirmwareUpdateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   current_version,   1)
#define moon_companion_v1_CheckFirmwareUpdateRequest_CALLBACK NULL
#define moon_companion_v1_CheckFirmwareUpdateRequest_DEFAULT NULL

#define moon_companion_v1_HttpGetRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   url,               1) \
X(a, STATIC,   REPEATED, MESSAGE,  headers,           2)
#define moon_companion_v1_HttpGetRequest_CALLBACK NULL
#define moon_companion_v1_HttpGetRequest_DEFAULT NULL
#define moon_companion_v1_HttpGetRequest_headers_MSGTYPE moon_companion_v1_HttpHeader

#define moon_companion_v1_HttpPostRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   url,               1) \
X(a, STATIC,   REPEATED, MESSAGE,  headers,           2) \
X(a, STATIC,   SINGULAR, BYTES,    body,              3)
#define moon_companion_v1_HttpPostRequest_CALLBACK NULL
#define moon_companion_v1_HttpPostRequest_DEFAULT NULL
#define moon_companion_v1_HttpPostRequest_headers_MSGTYPE moon_companion_v1_HttpHeader

#define moon_companion_v1_HttpHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2)
#define moon_companion_v1_HttpHeader_CALLBACK NULL
#define moon_companion_v1_HttpHeader_DEFAULT NULL

#define moon_companion_v1_HttpResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   status_code,       1) \
X(a, STATIC,   REPEATED, MESSAGE,  headers,           2) \
X(a, STATIC,   SINGULAR, BYTES,    body,              3)
#define moon_companion_v1_HttpResponse_CALLBACK NULL
#define moon_companion_v1_HttpResponse_DEFAULT NULL
#define moon_companion_v1_HttpResponse_headers_MSGTYPE moon_companion_v1_HttpHeader

extern const pb_msgdesc_t moon_companion_v1_MoonRequest_msg;
extern const pb_msgdesc_t moon_companion_v1_MoonResponse_msg;
extern const pb_msgdesc_t moon_companion_v1_MoonEvent_msg;
extern const pb_msgdesc_t moon_companion_v1_MoonPhoneMessage_msg;
extern const pb_msgdesc_t moon_companion_v1_PairRequest_msg;
extern const pb_msgdesc_t moon_companion_v1_PairResponse_msg;
extern const pb_msgdesc_t moon_companion_v1_GetPositionRequest_msg;
extern const pb_msgdesc_t moon_companion_v1_PositionData_msg;
extern const pb_msgdesc_t moon_companion_v1_SubscribePositionRequest_msg;
extern const pb_msgdesc_t moon_companion_v1_UnsubscribePositionRequest_msg;
extern const pb_msgdesc_t moon_companion_v1_GetTimeRequest_msg;
extern const pb_msgdesc_t moon_companion_v1_TimeData_msg;
extern const pb_msgdesc_t moon_companion_v1_SendNotificationRequest_msg;
extern const pb_msgdesc_t moon_companion_v1_NotificationAck_msg;
extern const pb_msgdesc_t moon_companion_v1_StatusAck_msg;
extern const pb_msgdesc_t moon_companion_v1_PhoneStatus_msg;
extern const pb_msgdesc_t moon_companion_v1_ListAppUpdatesRequest_msg;
extern const pb_msgdesc_t moon_companion_v1_AppVersion_msg;
extern const pb_msgdesc_t moon_companion_v1_UpdateList_msg;
extern const pb_msgdesc_t moon_companion_v1_AvailableUpdate_msg;
extern const pb_msgdesc_t moon_companion_v1_DownloadAppRequest_msg;
extern const pb_msgdesc_t moon_companion_v1_CheckFirmwareUpdateRequest_msg;
extern const pb_msgdesc_t moon_companion_v1_HttpGetRequest_msg;
extern const pb_msgdesc_t moon_companion_v1_HttpPostRequest_msg;
extern const pb_msgdesc_t moon_companion_v1_HttpHeader_msg;
extern const pb_msgdesc_t moon_companion_v1_HttpResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define moon_companion_v1_MoonRequest_fields &moon_companion_v1_MoonRequest_msg
#define moon_companion_v1_MoonResponse_fields &moon_companion_v1_MoonResponse_msg
#define moon_companion_v1_MoonEvent_fields &moon_companion_v1_MoonEvent_msg
#define moon_companion_v1_MoonPhoneMessage_fields &moon_companion_v1_MoonPhoneMessage_msg
#define moon_companion_v1_PairRequest_fields &moon_companion_v1_PairRequest_msg
#define moon_companion_v1_PairResponse_fields &moon_companion_v1_PairResponse_msg
#define moon_companion_v1_GetPositionRequest_fields &moon_companion_v1_GetPositionRequest_msg
#define moon_companion_v1_PositionData_fields &moon_companion_v1_PositionData_msg
#define moon_companion_v1_SubscribePositionRequest_fields &moon_companion_v1_SubscribePositionRequest_msg
#define moon_companion_v1_UnsubscribePositionRequest_fields &moon_companion_v1_UnsubscribePositionRequest_msg
#define moon_companion_v1_GetTimeRequest_fields &moon_companion_v1_GetTimeRequest_msg
#define moon_companion_v1_TimeData_fields &moon_companion_v1_TimeData_msg
#define moon_companion_v1_SendNotificationRequest_fields &moon_companion_v1_SendNotificationRequest_msg
#define moon_companion_v1_NotificationAck_fields &moon_companion_v1_NotificationAck_msg
#define moon_companion_v1_StatusAck_fields &moon_companion_v1_StatusAck_msg
#define moon_companion_v1_PhoneStatus_fields &moon_companion_v1_PhoneStatus_msg
#define moon_companion_v1_ListAppUpdatesRequest_fields &moon_companion_v1_ListAppUpdatesRequest_msg
#define moon_companion_v1_AppVersion_fields &moon_companion_v1_AppVersion_msg
#define moon_companion_v1_UpdateList_fields &moon_companion_v1_UpdateList_msg
#define moon_companion_v1_AvailableUpdate_fields &moon_companion_v1_AvailableUpdate_msg
#define moon_companion_v1_DownloadAppRequest_fields &moon_companion_v1_DownloadAppRequest_msg
#define moon_companion_v1_CheckFirmwareUpdateRequest_fields &moon_companion_v1_CheckFirmwareUpdateRequest_msg
#define moon_companion_v1_HttpGetRequest_fields &moon_companion_v1_HttpGetRequest_msg
#define moon_companion_v1_HttpPostRequest_fields &moon_companion_v1_HttpPostRequest_msg
#define moon_companion_v1_HttpHeader_fields &moon_companion_v1_HttpHeader_msg
#define moon_companion_v1_HttpResponse_fields &moon_companion_v1_HttpResponse_msg

/* Maximum encoded size of messages (where known) */
#define MOON_COMPANION_V1_MOON_COMPANION_PB_H_MAX_SIZE moon_companion_v1_MoonPhoneMessage_size
#define moon_companion_v1_AppVersion_size        50
#define moon_companion_v1_AvailableUpdate_size   186
#define moon_companion_v1_CheckFirmwareUpdateRequest_size 17
#define moon_companion_v1_DownloadAppRequest_size 163
#define moon_companion_v1_GetPositionRequest_size 6
#define moon_companion_v1_GetTimeRequest_size    0
#define moon_companion_v1_HttpGetRequest_size    794
#define moon_companion_v1_HttpHeader_size        163
#define moon_companion_v1_HttpPostRequest_size   925
#define moon_companion_v1_HttpResponse_size      801
#define moon_companion_v1_ListAppUpdatesRequest_size 416
#define moon_companion_v1_MoonEvent_size         65
#define moon_companion_v1_MoonPhoneMessage_size  1527
#define moon_companion_v1_MoonRequest_size       953
#define moon_companion_v1_MoonResponse_size      1524
#define moon_companion_v1_NotificationAck_size   2
#define moon_companion_v1_PairRequest_size       33
#define moon_companion_v1_PairResponse_size      51
#define moon_companion_v1_PhoneStatus_size       10
#define moon_companion_v1_PositionData_size      63
#define moon_companion_v1_SendNotificationRequest_size 262
#define moon_companion_v1_StatusAck_size         0
#define moon_companion_v1_SubscribePositionRequest_size 6
#define moon_companion_v1_TimeData_size          66
#define moon_companion_v1_UnsubscribePositionRequest_size 0
#define moon_companion_v1_UpdateList_size        1512

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
